config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :phones do
    get "delete"
  end
  resources :addresses
  root to: 'home#index'
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :phone, presence: true, numericality: { only_integer: true }
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  load_and_authorize_resource
  before_filter :check_role, :except => [:show, :new, :edit, :delete]
  before_filter :find_params, :only => [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @phone = Phone.new
  end

  def create
    @phone = Phone.create(phone_params)
  end

  def edit
  end

  def update
    @phone.update_attributes(phone_params)
  end

  def delete
    @phone = Phone.find(params[:phone_id])
  end

  def destroy
    @phone.destroy
  end

  private
  def phone_params
    params.require(:phone).permit(:phone, :user_id)
  end

  def check_role
    if User.find(current_user.id).role == 'admin'
      @phones = Phone.all
    else
      @phones = Phone.accessible_by(current_ability)
    end
  end

  def find_params
    @phone = Phone.find(params[:id])
  end

end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @phone.user.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes", phone_path(@phone), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/phones/_edit.html.erb
<%= render "form" %>

app/views/phones/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @phone, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <% if User.find(current_user.id).role == 'admin' %>
          <div class="form-group">
            <%= f.label :user_id, class:"control-label" %>
            <%= f.collection_select :user_id, User.all, :id, :name, {prompt: "Select user"}, {class: "form-control"} %>
          </div>
        <% else %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <% end %>
        <div class="form-group">
          <%= f.label :phone, class: "control-label" %>
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary", id: "btn-submit" %>
        <%= link_to "Cancel", "#", class: "btn btn-danger", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/phones/_index.html.erb
<% @phones.each do |phone| %>
  <tr>
    <td><%= phone.user.name %></td>
    <td><%= phone.phone %></td>
    <td><%= link_to "Edit", edit_phone_path(phone), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", phone_delete_path(phone), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/phones/_new.html.erb
<%= render "form" %>

app/views/phones/_save.js.erb
$("ul.errors").html("")
<% if @phone.errors.any? %>
  <% @phone.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".phone-index").html("<%= escape_javascript(render 'index') %>")
  $("#phone-modal").modal("hide")
<% end %>

app/views/phones/create.js.erb
<%= render "save" %>

app/views/phones/delete.js.erb
$("#phone-modal").html("<%= escape_javascript(render 'delete') %>")
$("#phone-modal").modal("show")

app/views/phones/destroy.js.erb
<%= render "save" %>

app/views/phones/edit.js.erb
$("#phone-modal").html("<%= escape_javascript(render 'edit') %>")
$("#phone-modal").modal("show")

app/views/phones/index.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= link_to "New Phonebook", new_phone_path, remote: true, class: "btn btn-primary", style:"color:#fff;" %></h3>
    </div>
    <div class="panel-body">
      <div class="new-phone"></div>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody class="phone-index">
          <%= render "index" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="phone-modal" class="modal fade"></div>

app/views/phones/new.js.erb
$("#phone-modal").html("<%= escape_javascript(render 'new') %>")
$("#phone-modal").modal("show")

app/views/phones/update.js.erb
<%= render "save" %>