config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :phones do
    get "delete"
  end
  resources :addresses
  root to: 'home#index'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  load_and_authorize_resource
  def index
    @addresses = Address.where(user_id: current_user.id)
  end

  def show

  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.create(address_params)
    @address.user_id = current_user.id
    if @address.save
      redirect_to addresses_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update_attributes(address_params)
      redirect_to addresses_path
    else
      render 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:address, :city, :user_id)
  end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit</h3>
  </div>
  <div class="panel-body">
    <%= form_for(@address) do |f| %>
    <% if @address.errors.any? %>
     <div id="error_explanation">
      <% @address.errors.full_messages.each do |message| %>
       <div class="alert alert-danger alert-dismissible fade in" role=alert>
         <button type=button class=close data-dismiss=alert aria-label=Close><span aria-hidden=true>&times;</span></button>
         <%= message %>
       </div>
      <% end %>
     </div>
    <% end %>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :address,class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city,class: 'form-control' %>
      </div>

      <%= f.submit "Save", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/addresses/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Address <%= link_to "New", new_address_path, class: "btn btn-success btn-xs" %></h3>
  </div>
  <div class="panel-body">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Address</th>
          <th>City</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @addresses.each do |address| %>
          <tr>
            <td><%= address.address %></td>
            <td><%= address.city %></td>
            <td>
              <div class="btn-group btn-group-sm">
                <%= link_to "Detail", edit_address_path(address), class: 'btn btn-primary' %>
                <%= link_to "Delete", address, class: 'btn btn-danger', method: :delete,
                                                                        data: {confirm: 'Are you sure?'} %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Address</h3>
  </div>
  <div class="panel-body">

    <%= form_for(@address) do |f| %>
    <% if @address.errors.any? %>
     <div id="error_explanation">
      <% @address.errors.full_messages.each do |message| %>
       <div class="alert alert-danger alert-dismissible fade in" role=alert>
         <button type=button class=close data-dismiss=alert aria-label=Close><span aria-hidden=true>&times;</span></button>
         <%= message %>
       </div>
      <% end %>
     </div>
    <% end %>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :address,class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city,class: 'form-control' %>
      </div>

      <%= f.submit "Save", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>