config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :phones do
    get "delete"
  end
  resources :addresses
  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Phonebooks</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
       <div class="container">
         <div class="navbar-header">
            <a class="navbar-brand" href="#">Phonebook</a>
         </div>
         <ul class="nav navbar-nav">
         </ul>
         <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Address" , addresses_path %></li>
            <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign In", user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
            <% end %>
         </ul>
       </div>
    </div>
    <div class="container">
       <% flash.each do |type, message| %>
       <div class="alert <%= flash_class type %> alert-dismissable">
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
         <p><%= message %></p>
       </div>
       <% end %>

       <%= yield %>
    </div>
  </body>
  </html>